services:
  rust_server:
    build:
      context: ./rust_server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  kong:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - rust_server